// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mail.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SenderMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SenderMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* MailMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MailMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* CheckIdReturnMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CheckIdReturnMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* SendMailReturnMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SendMailReturnMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* FuncType_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FuncType_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mail_2eproto() {
  protobuf_AddDesc_mail_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mail.proto");
  GOOGLE_CHECK(file != NULL);
  SenderMsg_descriptor_ = file->message_type(0);
  static const int SenderMsg_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, sendername_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, sendermailname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, smtpsvrname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, smtpsvrport_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, base64name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, base64passwd_),
  };
  SenderMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SenderMsg_descriptor_,
      SenderMsg::default_instance_,
      SenderMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SenderMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SenderMsg));
  MailMsg_descriptor_ = file->message_type(1);
  static const int MailMsg_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MailMsg, receivername_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MailMsg, mailsubject_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MailMsg, mailcontent_),
  };
  MailMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MailMsg_descriptor_,
      MailMsg::default_instance_,
      MailMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MailMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MailMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MailMsg));
  CheckIdReturnMsg_descriptor_ = file->message_type(2);
  static const int CheckIdReturnMsg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckIdReturnMsg, error_code_),
  };
  CheckIdReturnMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CheckIdReturnMsg_descriptor_,
      CheckIdReturnMsg::default_instance_,
      CheckIdReturnMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckIdReturnMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CheckIdReturnMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CheckIdReturnMsg));
  SendMailReturnMsg_descriptor_ = file->message_type(3);
  static const int SendMailReturnMsg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SendMailReturnMsg, error_code_),
  };
  SendMailReturnMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SendMailReturnMsg_descriptor_,
      SendMailReturnMsg::default_instance_,
      SendMailReturnMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SendMailReturnMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SendMailReturnMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SendMailReturnMsg));
  FuncType_descriptor_ = file->message_type(4);
  static const int FuncType_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FuncType, msg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FuncType, type_),
  };
  FuncType_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FuncType_descriptor_,
      FuncType::default_instance_,
      FuncType_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FuncType, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FuncType, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FuncType));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mail_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SenderMsg_descriptor_, &SenderMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MailMsg_descriptor_, &MailMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CheckIdReturnMsg_descriptor_, &CheckIdReturnMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SendMailReturnMsg_descriptor_, &SendMailReturnMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FuncType_descriptor_, &FuncType::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mail_2eproto() {
  delete SenderMsg::default_instance_;
  delete SenderMsg_reflection_;
  delete MailMsg::default_instance_;
  delete MailMsg_reflection_;
  delete CheckIdReturnMsg::default_instance_;
  delete CheckIdReturnMsg_reflection_;
  delete SendMailReturnMsg::default_instance_;
  delete SendMailReturnMsg_reflection_;
  delete FuncType::default_instance_;
  delete FuncType_reflection_;
}

void protobuf_AddDesc_mail_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nmail.proto\"\213\001\n\tSenderMsg\022\022\n\nsenderName"
    "\030\001 \002(\t\022\026\n\016senderMailName\030\002 \002(\t\022\023\n\013smtpSv"
    "rName\030\003 \002(\t\022\023\n\013smtpSvrPort\030\004 \002(\005\022\022\n\nbase"
    "64Name\030\005 \002(\t\022\024\n\014base64Passwd\030\006 \002(\t\"I\n\007Ma"
    "ilMsg\022\024\n\014receiverName\030\001 \002(\t\022\023\n\013mailSubje"
    "ct\030\002 \002(\t\022\023\n\013mailContent\030\003 \002(\t\"&\n\020CheckId"
    "ReturnMsg\022\022\n\nerror_code\030\001 \002(\005\"\'\n\021SendMai"
    "lReturnMsg\022\022\n\nerror_code\030\001 \002(\005\"%\n\010FuncTy"
    "pe\022\013\n\003msg\030\001 \002(\t\022\014\n\004type\030\002 \002(\005", 349);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mail.proto", &protobuf_RegisterTypes);
  SenderMsg::default_instance_ = new SenderMsg();
  MailMsg::default_instance_ = new MailMsg();
  CheckIdReturnMsg::default_instance_ = new CheckIdReturnMsg();
  SendMailReturnMsg::default_instance_ = new SendMailReturnMsg();
  FuncType::default_instance_ = new FuncType();
  SenderMsg::default_instance_->InitAsDefaultInstance();
  MailMsg::default_instance_->InitAsDefaultInstance();
  CheckIdReturnMsg::default_instance_->InitAsDefaultInstance();
  SendMailReturnMsg::default_instance_->InitAsDefaultInstance();
  FuncType::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mail_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mail_2eproto {
  StaticDescriptorInitializer_mail_2eproto() {
    protobuf_AddDesc_mail_2eproto();
  }
} static_descriptor_initializer_mail_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SenderMsg::kSenderNameFieldNumber;
const int SenderMsg::kSenderMailNameFieldNumber;
const int SenderMsg::kSmtpSvrNameFieldNumber;
const int SenderMsg::kSmtpSvrPortFieldNumber;
const int SenderMsg::kBase64NameFieldNumber;
const int SenderMsg::kBase64PasswdFieldNumber;
#endif  // !_MSC_VER

SenderMsg::SenderMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SenderMsg::InitAsDefaultInstance() {
}

SenderMsg::SenderMsg(const SenderMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SenderMsg::SharedCtor() {
  _cached_size_ = 0;
  sendername_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  sendermailname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  smtpsvrname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  smtpsvrport_ = 0;
  base64name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  base64passwd_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SenderMsg::~SenderMsg() {
  SharedDtor();
}

void SenderMsg::SharedDtor() {
  if (sendername_ != &::google::protobuf::internal::kEmptyString) {
    delete sendername_;
  }
  if (sendermailname_ != &::google::protobuf::internal::kEmptyString) {
    delete sendermailname_;
  }
  if (smtpsvrname_ != &::google::protobuf::internal::kEmptyString) {
    delete smtpsvrname_;
  }
  if (base64name_ != &::google::protobuf::internal::kEmptyString) {
    delete base64name_;
  }
  if (base64passwd_ != &::google::protobuf::internal::kEmptyString) {
    delete base64passwd_;
  }
  if (this != default_instance_) {
  }
}

void SenderMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SenderMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SenderMsg_descriptor_;
}

const SenderMsg& SenderMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mail_2eproto();
  return *default_instance_;
}

SenderMsg* SenderMsg::default_instance_ = NULL;

SenderMsg* SenderMsg::New() const {
  return new SenderMsg;
}

void SenderMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_sendername()) {
      if (sendername_ != &::google::protobuf::internal::kEmptyString) {
        sendername_->clear();
      }
    }
    if (has_sendermailname()) {
      if (sendermailname_ != &::google::protobuf::internal::kEmptyString) {
        sendermailname_->clear();
      }
    }
    if (has_smtpsvrname()) {
      if (smtpsvrname_ != &::google::protobuf::internal::kEmptyString) {
        smtpsvrname_->clear();
      }
    }
    smtpsvrport_ = 0;
    if (has_base64name()) {
      if (base64name_ != &::google::protobuf::internal::kEmptyString) {
        base64name_->clear();
      }
    }
    if (has_base64passwd()) {
      if (base64passwd_ != &::google::protobuf::internal::kEmptyString) {
        base64passwd_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SenderMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string senderName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sendername()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sendername().data(), this->sendername().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_senderMailName;
        break;
      }

      // required string senderMailName = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_senderMailName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sendermailname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sendermailname().data(), this->sendermailname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_smtpSvrName;
        break;
      }

      // required string smtpSvrName = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_smtpSvrName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_smtpsvrname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->smtpsvrname().data(), this->smtpsvrname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_smtpSvrPort;
        break;
      }

      // required int32 smtpSvrPort = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_smtpSvrPort:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &smtpsvrport_)));
          set_has_smtpsvrport();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_base64Name;
        break;
      }

      // required string base64Name = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_base64Name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_base64name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->base64name().data(), this->base64name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_base64Passwd;
        break;
      }

      // required string base64Passwd = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_base64Passwd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_base64passwd()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->base64passwd().data(), this->base64passwd().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SenderMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string senderName = 1;
  if (has_sendername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sendername().data(), this->sendername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->sendername(), output);
  }

  // required string senderMailName = 2;
  if (has_sendermailname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sendermailname().data(), this->sendermailname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->sendermailname(), output);
  }

  // required string smtpSvrName = 3;
  if (has_smtpsvrname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->smtpsvrname().data(), this->smtpsvrname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->smtpsvrname(), output);
  }

  // required int32 smtpSvrPort = 4;
  if (has_smtpsvrport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->smtpsvrport(), output);
  }

  // required string base64Name = 5;
  if (has_base64name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base64name().data(), this->base64name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->base64name(), output);
  }

  // required string base64Passwd = 6;
  if (has_base64passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base64passwd().data(), this->base64passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->base64passwd(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SenderMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string senderName = 1;
  if (has_sendername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sendername().data(), this->sendername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->sendername(), target);
  }

  // required string senderMailName = 2;
  if (has_sendermailname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sendermailname().data(), this->sendermailname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sendermailname(), target);
  }

  // required string smtpSvrName = 3;
  if (has_smtpsvrname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->smtpsvrname().data(), this->smtpsvrname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->smtpsvrname(), target);
  }

  // required int32 smtpSvrPort = 4;
  if (has_smtpsvrport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->smtpsvrport(), target);
  }

  // required string base64Name = 5;
  if (has_base64name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base64name().data(), this->base64name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->base64name(), target);
  }

  // required string base64Passwd = 6;
  if (has_base64passwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base64passwd().data(), this->base64passwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->base64passwd(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SenderMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string senderName = 1;
    if (has_sendername()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sendername());
    }

    // required string senderMailName = 2;
    if (has_sendermailname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sendermailname());
    }

    // required string smtpSvrName = 3;
    if (has_smtpsvrname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->smtpsvrname());
    }

    // required int32 smtpSvrPort = 4;
    if (has_smtpsvrport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->smtpsvrport());
    }

    // required string base64Name = 5;
    if (has_base64name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->base64name());
    }

    // required string base64Passwd = 6;
    if (has_base64passwd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->base64passwd());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SenderMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SenderMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SenderMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SenderMsg::MergeFrom(const SenderMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sendername()) {
      set_sendername(from.sendername());
    }
    if (from.has_sendermailname()) {
      set_sendermailname(from.sendermailname());
    }
    if (from.has_smtpsvrname()) {
      set_smtpsvrname(from.smtpsvrname());
    }
    if (from.has_smtpsvrport()) {
      set_smtpsvrport(from.smtpsvrport());
    }
    if (from.has_base64name()) {
      set_base64name(from.base64name());
    }
    if (from.has_base64passwd()) {
      set_base64passwd(from.base64passwd());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SenderMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SenderMsg::CopyFrom(const SenderMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SenderMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  return true;
}

void SenderMsg::Swap(SenderMsg* other) {
  if (other != this) {
    std::swap(sendername_, other->sendername_);
    std::swap(sendermailname_, other->sendermailname_);
    std::swap(smtpsvrname_, other->smtpsvrname_);
    std::swap(smtpsvrport_, other->smtpsvrport_);
    std::swap(base64name_, other->base64name_);
    std::swap(base64passwd_, other->base64passwd_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SenderMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SenderMsg_descriptor_;
  metadata.reflection = SenderMsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MailMsg::kReceiverNameFieldNumber;
const int MailMsg::kMailSubjectFieldNumber;
const int MailMsg::kMailContentFieldNumber;
#endif  // !_MSC_VER

MailMsg::MailMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MailMsg::InitAsDefaultInstance() {
}

MailMsg::MailMsg(const MailMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MailMsg::SharedCtor() {
  _cached_size_ = 0;
  receivername_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  mailsubject_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  mailcontent_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MailMsg::~MailMsg() {
  SharedDtor();
}

void MailMsg::SharedDtor() {
  if (receivername_ != &::google::protobuf::internal::kEmptyString) {
    delete receivername_;
  }
  if (mailsubject_ != &::google::protobuf::internal::kEmptyString) {
    delete mailsubject_;
  }
  if (mailcontent_ != &::google::protobuf::internal::kEmptyString) {
    delete mailcontent_;
  }
  if (this != default_instance_) {
  }
}

void MailMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MailMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MailMsg_descriptor_;
}

const MailMsg& MailMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mail_2eproto();
  return *default_instance_;
}

MailMsg* MailMsg::default_instance_ = NULL;

MailMsg* MailMsg::New() const {
  return new MailMsg;
}

void MailMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_receivername()) {
      if (receivername_ != &::google::protobuf::internal::kEmptyString) {
        receivername_->clear();
      }
    }
    if (has_mailsubject()) {
      if (mailsubject_ != &::google::protobuf::internal::kEmptyString) {
        mailsubject_->clear();
      }
    }
    if (has_mailcontent()) {
      if (mailcontent_ != &::google::protobuf::internal::kEmptyString) {
        mailcontent_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MailMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string receiverName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_receivername()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->receivername().data(), this->receivername().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_mailSubject;
        break;
      }

      // required string mailSubject = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mailSubject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mailsubject()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->mailsubject().data(), this->mailsubject().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_mailContent;
        break;
      }

      // required string mailContent = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mailContent:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mailcontent()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->mailcontent().data(), this->mailcontent().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MailMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string receiverName = 1;
  if (has_receivername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->receivername().data(), this->receivername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->receivername(), output);
  }

  // required string mailSubject = 2;
  if (has_mailsubject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->mailsubject().data(), this->mailsubject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->mailsubject(), output);
  }

  // required string mailContent = 3;
  if (has_mailcontent()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->mailcontent().data(), this->mailcontent().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->mailcontent(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MailMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string receiverName = 1;
  if (has_receivername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->receivername().data(), this->receivername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->receivername(), target);
  }

  // required string mailSubject = 2;
  if (has_mailsubject()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->mailsubject().data(), this->mailsubject().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->mailsubject(), target);
  }

  // required string mailContent = 3;
  if (has_mailcontent()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->mailcontent().data(), this->mailcontent().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->mailcontent(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MailMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string receiverName = 1;
    if (has_receivername()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->receivername());
    }

    // required string mailSubject = 2;
    if (has_mailsubject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->mailsubject());
    }

    // required string mailContent = 3;
    if (has_mailcontent()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->mailcontent());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MailMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MailMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MailMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MailMsg::MergeFrom(const MailMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_receivername()) {
      set_receivername(from.receivername());
    }
    if (from.has_mailsubject()) {
      set_mailsubject(from.mailsubject());
    }
    if (from.has_mailcontent()) {
      set_mailcontent(from.mailcontent());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MailMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MailMsg::CopyFrom(const MailMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MailMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void MailMsg::Swap(MailMsg* other) {
  if (other != this) {
    std::swap(receivername_, other->receivername_);
    std::swap(mailsubject_, other->mailsubject_);
    std::swap(mailcontent_, other->mailcontent_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MailMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MailMsg_descriptor_;
  metadata.reflection = MailMsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CheckIdReturnMsg::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

CheckIdReturnMsg::CheckIdReturnMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CheckIdReturnMsg::InitAsDefaultInstance() {
}

CheckIdReturnMsg::CheckIdReturnMsg(const CheckIdReturnMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CheckIdReturnMsg::SharedCtor() {
  _cached_size_ = 0;
  error_code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CheckIdReturnMsg::~CheckIdReturnMsg() {
  SharedDtor();
}

void CheckIdReturnMsg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CheckIdReturnMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CheckIdReturnMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CheckIdReturnMsg_descriptor_;
}

const CheckIdReturnMsg& CheckIdReturnMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mail_2eproto();
  return *default_instance_;
}

CheckIdReturnMsg* CheckIdReturnMsg::default_instance_ = NULL;

CheckIdReturnMsg* CheckIdReturnMsg::New() const {
  return new CheckIdReturnMsg;
}

void CheckIdReturnMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_code_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CheckIdReturnMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 error_code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
          set_has_error_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CheckIdReturnMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 error_code = 1;
  if (has_error_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CheckIdReturnMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 error_code = 1;
  if (has_error_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error_code(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CheckIdReturnMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 error_code = 1;
    if (has_error_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->error_code());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CheckIdReturnMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CheckIdReturnMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CheckIdReturnMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CheckIdReturnMsg::MergeFrom(const CheckIdReturnMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_code()) {
      set_error_code(from.error_code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CheckIdReturnMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CheckIdReturnMsg::CopyFrom(const CheckIdReturnMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CheckIdReturnMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CheckIdReturnMsg::Swap(CheckIdReturnMsg* other) {
  if (other != this) {
    std::swap(error_code_, other->error_code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CheckIdReturnMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CheckIdReturnMsg_descriptor_;
  metadata.reflection = CheckIdReturnMsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SendMailReturnMsg::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

SendMailReturnMsg::SendMailReturnMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SendMailReturnMsg::InitAsDefaultInstance() {
}

SendMailReturnMsg::SendMailReturnMsg(const SendMailReturnMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SendMailReturnMsg::SharedCtor() {
  _cached_size_ = 0;
  error_code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SendMailReturnMsg::~SendMailReturnMsg() {
  SharedDtor();
}

void SendMailReturnMsg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SendMailReturnMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SendMailReturnMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SendMailReturnMsg_descriptor_;
}

const SendMailReturnMsg& SendMailReturnMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mail_2eproto();
  return *default_instance_;
}

SendMailReturnMsg* SendMailReturnMsg::default_instance_ = NULL;

SendMailReturnMsg* SendMailReturnMsg::New() const {
  return new SendMailReturnMsg;
}

void SendMailReturnMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_code_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SendMailReturnMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 error_code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
          set_has_error_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SendMailReturnMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 error_code = 1;
  if (has_error_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SendMailReturnMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 error_code = 1;
  if (has_error_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error_code(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SendMailReturnMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 error_code = 1;
    if (has_error_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->error_code());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SendMailReturnMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SendMailReturnMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SendMailReturnMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SendMailReturnMsg::MergeFrom(const SendMailReturnMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_code()) {
      set_error_code(from.error_code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SendMailReturnMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SendMailReturnMsg::CopyFrom(const SendMailReturnMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendMailReturnMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void SendMailReturnMsg::Swap(SendMailReturnMsg* other) {
  if (other != this) {
    std::swap(error_code_, other->error_code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SendMailReturnMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SendMailReturnMsg_descriptor_;
  metadata.reflection = SendMailReturnMsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FuncType::kMsgFieldNumber;
const int FuncType::kTypeFieldNumber;
#endif  // !_MSC_VER

FuncType::FuncType()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FuncType::InitAsDefaultInstance() {
}

FuncType::FuncType(const FuncType& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FuncType::SharedCtor() {
  _cached_size_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FuncType::~FuncType() {
  SharedDtor();
}

void FuncType::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void FuncType::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FuncType::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FuncType_descriptor_;
}

const FuncType& FuncType::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mail_2eproto();
  return *default_instance_;
}

FuncType* FuncType::default_instance_ = NULL;

FuncType* FuncType::New() const {
  return new FuncType;
}

void FuncType::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msg()) {
      if (msg_ != &::google::protobuf::internal::kEmptyString) {
        msg_->clear();
      }
    }
    type_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FuncType::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string msg = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_type;
        break;
      }

      // required int32 type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FuncType::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msg(), output);
  }

  // required int32 type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FuncType::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  // required int32 type = 2;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FuncType::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string msg = 1;
    if (has_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg());
    }

    // required int32 type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FuncType::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FuncType* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FuncType*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FuncType::MergeFrom(const FuncType& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg()) {
      set_msg(from.msg());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FuncType::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FuncType::CopyFrom(const FuncType& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FuncType::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void FuncType::Swap(FuncType* other) {
  if (other != this) {
    std::swap(msg_, other->msg_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FuncType::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FuncType_descriptor_;
  metadata.reflection = FuncType_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
